### ISSUE TITLE
Players log in again while already logged in. And then kill their old self and duplicate items.

### ISSUE THREAD

**Issue by Anna-28** [CanaryModTeam/CanaryMod#110]
So far this has happened to me a few times. this is exactly what happened in order:

First, normally playing minecraft, then my internet decides to do something and I lose connection to things like teamspeak and minecraft servers.
Minecraft tells me I timed out.
Internet fixes within a few seconds and then I rejoin the server (The server thinks I am still on it though).
I log in to the server and see another me, standing where I was when I logged in. I can punch and hurt and kill this other me and it will drop all the items it had. After a few seconds it will disconnect from the server though.

Trying to join with a second client normally would kick the first one if it is logged in already. In chat it would say "Player joined the game" and then "Player left the game" right after it. The joining is the second client and the leaving is the first, so the second is still ingame.
The message the first client gets when the second logs in is "You logged in from another location"

**Comment by darkdiplomat** [comment]
Since this is a 1.7.10 issue and we have stopped working on 1.7.10 builds, this is being closed.
