### ISSUE TITLE
[Bleeding] ItemPickupHook doesn't fire

### ISSUE THREAD

**Issue by mikeboers** [CanaryModTeam/CanaryMod#159]
I'm not 100% on this one, but it seems like the code to fire ItemPickupHook exists in `InventoryPlayer.canPickup(EntityItem)`, but not in `InventoryPlayer.a(ItemStack)` (which, according to the comments, is the real deal).

**Comment by darkdiplomat** [comment]
This has already been address https://github.com/CanaryModTeam/CanaryMod/commit/5aa56827cf28039c6f9c859aba140624382e547e

**Comment by mikeboers** [comment]
Oh, okay; great!

I know this isn't the place for such questions, but (I'll plow through it anyways): is there a hook for placing/removing items into/from chests?

**Comment by darkdiplomat** [comment]
InventoryHook along with SlotClickedHook

**Comment by mikeboers** [comment]
Those are exactly the ones; I didn't see SlotClickedHook somehow.
