### ISSUE TITLE
[BLEEDING] build 183, trading with villagers returns your trade plus their offer!

### ISSUE THREAD

**Issue by gerardvanschip** [CanaryModTeam/CanaryMod#161]
So a villager asks for 23 paper and will give 2 emeralds. I give paper, take emerald and then when the window closes my 23 paper drops which I can pick up. No paper lost but gained emeralds.

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryMod/issues/156

(Bleeding has merged with Master, https://ci.visualillusionsent.net/job/CanaryMod/ )
