### ISSUE TITLE
[BLEEDING] build 183, trading with villagers does not make them happy

### ISSUE THREAD

**Issue by gerardvanschip** [CanaryModTeam/CanaryMod#162]
In vanilla Minecraft you need to trade with villagers to make them happy and start breeding. When you trade you see a particle animations indicating they are happy. I see no such thing in canarymod?

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryMod/issues/156

(Bleeding has merged with Master, https://ci.visualillusionsent.net/job/CanaryMod/ )
