### ISSUE TITLE
No World.getTime() method 

### ISSUE THREAD

**Issue by walterhiggins** [CanaryModTeam/CanaryMod#164]
There's a setTime() method but no getTime() method. 
How do you reliably get the current time of day in Minecraft using world.getTotalTime() ?

**Comment by darkdiplomat** [comment]
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/World.html#getRelativeTime()
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/net/canarymod/api/world/World.html#getRawTime()

**Comment by walterhiggins** [comment]
OK. I've looked over this and I'm still at a loss as to how to *get* the time of day in CanaryMod.
I don't see any relationship between getRelativeTime(), getRawTime() and the time-of-day.
Can you add a world.getTime() method which corresponds to world.setTime() ?
http://minecraft.gamepedia.com/Day-night_cycle#Conversions

I'm guessing that world.setTime() is doing something strange because when I call that method, the world.totalTime is set to a huge number (bigger than world.rawTime).

If I call /time set 6000 then the world.getTotalTime() method returns a time I'd expect (according to that conversion chart). It's most likely that world.setTime() is doing something it shouldn't. I can workaround this in my plugin I guess but it would be nice to have a world.getTime() that consistently returned day ticks.
