### ISSUE TITLE
command block appears to filter/output redstone signals incorrectly

### ISSUE THREAD

**Issue by jmbjorndalen** [CanaryModTeam/CanaryMod#165]
Given a setup like the following: 

    redstone pulse -> command block -> redstone comparator/repeater

And the following command in the command block: 

   /testfor @p[10,65,10,r=1] 

On Canary (1.7.10-1.1.3), the redstone pulse is just propagated by the command block, much like any solid block would do. There is no filtering based on the player detection. The player detection appears to work correctly when I read check the "Previous Output" field in the command block, so the block _does_ detect whether a player is in the correct location. 

The command block should have created a redstone output signal based on the /testfor command, but it doesn't.  A simplified version (that works in standard 1.7.10) is as follows: https://www.youtube.com/watch?v=S2wU2Gm3Ouc

I found this when trying to figure out why a Christmas map didn't work properly with the CanaryMod server. 

The following is set in config/server.cfg: 
command-block-enabled=true
command-block-op=true

Regards, 
JM

**Comment by svdragster** [comment]
In the 1.8 version of canary this is working fine.

**Comment by jmbjorndalen** [comment]
Yes, looks like the 1.8 version solves the problem. Thanks :-)

**Comment by darkdiplomat** [comment]
1.7.10 is no longer under active development
