### ISSUE TITLE
1.2 invisible potion makes you transparent, not invisible

### ISSUE THREAD

**Issue by gerardvanschip** [CanaryModTeam/CanaryMod#166]
This is recent. Was ok in the bleeding builds. Just to clarify, people can clearly see you and your name is still above your head.

**Comment by darkdiplomat** [comment]
In my tests, i am completely invisible aside from the particle effects of the potion itself

**Comment by gerardvanschip** [comment]
Ah, in that case I will unload my plugins, see if its one of those.
