### ISSUE TITLE
Strange behaviour of mobs with BaseTags

### ISSUE THREAD

**Issue by svdragster** [CanaryModTeam/CanaryMod#168]
Adding a compoundTag.put("Silent", true); will freeze them and it's not possible to kill them by hand.
Adding this before spawning the mob the mob won't even appear in the world, you can also not move/teleport the mob around.

**Comment by darkdiplomat** [comment]
I am assuming here that you aren't setting up the entire NBTTags correctly,
you should getNBT(), manipluate that tag with the new data and settings, then setNBT(tag) so that all proper tags remain inside the base tag.

**Comment by svdragster** [comment]
That was the problem, thanks.
