### ISSUE TITLE
Build #183: removeAllPotionEffects() not removing effects

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#171]
removeAllPotionEffects() is not removing potion effects.

**Comment by gerardvanschip** [comment]
Build 183 has been replaced by the release 663 build which includes fixes.
https://ci.visualillusionsent.net/job/CanaryMod/

**Comment by toddharrison** [comment]
I have confirmed that this bug still exists in build 668. Specifically, I'm trying to remove the potion effects from a player and reapply them from a save, if applicable. I'm running this code:
```
PlayerStatePlugin.logger.info("*** potion effects before: " + player.getAllActivePotionEffects().size());
player.removeAllPotionEffects();
PlayerStatePlugin.logger.info("*** potion effects after: " + player.getAllActivePotionEffects().size());
```
The output I see in the log is:
```
[18:28:08] [PlayerState] [INFO]: *** potion effects before: 1
[18:28:08] [PlayerState] [INFO]: *** potion effects after: 1
```
and the effect stays on the player when there should be no potion effects.

**Comment by darkdiplomat** [comment]
I tested this and found that effects are being removed, Size of active effects may be an inaccurate determination of effects applied to a user as there may be 'nulls' slipping in

**Comment by darkdiplomat** [comment]
further examination, it does remove effects but the list itself is returning invalid data
