### ISSUE TITLE
Build #183: setExperience() not overwriting current experience

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#172]
setExperience() is not overwriting the current experience and is instead behaving like addExperience().

**Comment by gerardvanschip** [comment]
Build 183 has been replaced by the release 663 build which includes fixes.
https://ci.visualillusionsent.net/job/CanaryMod/

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryMod/commit/841e5f9439a808309bfa71dee6b3b25f9186d9dc
https://github.com/CanaryModTeam/CanaryMod/commit/3be2646f9e73bcf0c2b874202402a942181eca93
