### ISSUE TITLE
Build #183: Player.isDead() returning true when teleporting to new worlds

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#174]
The Player.isDead() method is returning true even when the player has not died, for example when switching worlds using a command and the PlayerRespawningHook to check isDead().

**Comment by svdragster** [comment]
That's probably how it works. PlayerRespawnedHook also calls when a player is logging in.

**Comment by gerardvanschip** [comment]
Build 183 has been replaced by the release 663 build which includes fixes.
https://ci.visualillusionsent.net/job/CanaryMod/

**Comment by darkdiplomat** [comment]
A player is technically killed and regenerated in the new world during any dimensional or world switching activities. It's vanilla behavior.
