### ISSUE TITLE
XML Database throws NullPointerException on data load

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#178]
Inside of my PlayerState plugin I am attempting to load the player data from the database upon server startup. This is resulting in a NullPointerException from the XmlDatabase class. The method I'm calling is: `Database.get().load(playerDao, filters);` 

I have confirmed that Database.git(), playerDao, and filters are all not null and what I would expect. I've confirmed the filters against the appropriate XML database file and it should be returning a result.

The full stack trace is here:
http://pastebin.com/ZPcGkj0g
Look at the caused by exception specifically.

This only seems to be causing a problem when I try to load the data, saving it works correctly.

**Comment by darkdiplomat** [comment]
It looks to be related to default values as your field names don't match the actual columns names to exact case, so when it does a default value look up it freaks out.
I'll have to rethink the default value stuff.

**Comment by darkdiplomat** [comment]
oh wait, thats not the issue at all, its with the change in how xml table properties are stored, (though that other thing could be an issue in the near future as well)

**Comment by toddharrison** [comment]
Your change in b674 seems to have done the trick. I'm loading without exceptions now. Thanks!
