### ISSUE TITLE
Piston Extend and Retract Hooks .getMoving().getType() returning BlockType.Air regardless of the block?

### ISSUE THREAD

**Issue by clucky** [CanaryModTeam/CanaryMod#185]
Not sure if I'm using it correctly, but I'm trying to make it so when a piston pushes an emerald block, it breaks the block and drops the item. However, when I listen to PistonExtendHook and do `hook.getMoving().getType()` it returns BlockType.Air regardless of the block that it is pushing. PistonRetractHook is not working properly either, leading me to believe it is having the same issue. I'm using one of the bleeding CanaryMod versions (one of the newer ones, about 4-7 days old) for 1.8.

The code I am trying to use is as follows, in case you want to verify that it is being attempted correctly:
````
public class LandListeners implements PluginListener{
	@HookHandler
	public void onPistonExtend(PistonExtendHook hook) {
		ColonyCraft.logger.debug("Moving block: " + hook.getMoving().getType().getData());
		if (hook.getMoving().getType() == BlockType.EmeraldBlock) {
			hook.getMoving().dropBlockAsItem(true);
		}
	}
	
	@HookHandler
	public void onPistonRetract(PistonRetractHook hook) {
		ColonyCraft.logger.debug("Moving block: " + hook.getMoving().getType().getData());
		if (hook.getMoving().getType() == BlockType.EmeraldBlock) {
			hook.getMoving().dropBlockAsItem(true);
		}
	}
}
````

Console output upon placing a redstone torch beside a piston with an emerald block in front of it and breaking the torch immediately after piston expansion:

````
[00:59:01] [ColonyCraft] [DEBUG]: Moving block: 0
[00:59:06] [ColonyCraft] [DEBUG]: Moving block: 0
[00:59:06] [ColonyCraft] [DEBUG]: Moving block: 0
```

**Comment by clucky** [comment]
As well, doing hook.setCanceled() for either of these does not result in the piston not moving, the action still occurs.

**Comment by clucky** [comment]
Also, as it can be seen by console output, the PistonExtendHook is being triggered twice upon piston expansion.

**Comment by darkdiplomat** [comment]
oh i see, its reading the wrong side of the piston
