### ISSUE TITLE
folders: db & databases

### ISSUE THREAD

**Issue by sennewood** [CanaryModTeam/CanaryMod#194]
Every file exists in "db" and "databases" is empty. In order to not confuse people the empty one should not more be generated if he's not needed.

**Comment by darkdiplomat** [comment]
Databases folder was intended for database adapters, a name change probably should take place though

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryLib/commit/2cc3191ac7c006dcd7c755b729b9013b5b7e731c
forgot to set it in the message
