### ISSUE TITLE
ServerListPingHook setCurrentPlayers

### ISSUE THREAD

**Issue by svdragster** [CanaryModTeam/CanaryMod#198]
hook.setCurrentPlayers(hook.getMaxPlayers() - 1);

In the server list when 1 player is online:
http://i.imgur.com/eg86wy0.jpg

**Comment by jamierocks** [comment]
Looks like you set it to 11 players.

**Comment by svdragster** [comment]
If I set it to 2 it actually displays 12 players online

**Comment by svdragster** [comment]
Actually the server list did not update properly.
