### ISSUE TITLE
Guardians calling EntityDespawnHook but don't despawn 

### ISSUE THREAD

**Issue by svdragster** [CanaryModTeam/CanaryMod#202]
Guardians are trying to constantly despawn in any circumstances, even in water. However even if you don't cancel the hook or anything they won't despawn but are still calling the hook.

**Comment by darkdiplomat** [comment]
Before I close this out, just want to double check if the issues is still happening or seems to have been corrected.

**Comment by svdragster** [comment]
Not an issue anymore
