### ISSUE TITLE
Player.getExperience() not returning correct value

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryMod#227]
Recently (since somewhere around 805) the Player.getExperience() method has started returning the incorrect value for the experience of the Player. After enchanting an item, it still returns the experience value before the item was enchanted.

**Comment by Larry1123** [comment]
Do you have any more info about this?

**Comment by toddharrison** [comment]
Just tried to replicate it using a simple plugin. Looks like it's gotten fixed. Considering that CanaryMod hasn't changed since I discovered the issue, I'd assume the bug was somewhere in Minecraft itself.
